"""The published contract is scoped to one rule set version, and why.

The measurement that produced this decision, reproduced here as a test so it
cannot quietly stop being true: adding a single rule to the current document,
changing nothing else, destroys **all forty-seven** published ``finding_key``
values and rewrites seven of the nine published artifacts. Not some of them —
the published ``run_id`` is a digest of the rule document's bytes, so any rule
anywhere re-keys every finding everywhere.

What makes that fatal rather than untidy is what it takes down with it:
``docs/evidence/stage_3b/acceptance_manifest.json`` pins those digests and can
only be regenerated by re-capturing screenshots by hand in Power BI Desktop.
Growing the rule library would have been blocked on a task deferred to Phase 5.

So the published files mean *what rule set 0.1 said about one project*. Both
halves are scope, and both are configuration rather than assumption.
"""

from __future__ import annotations

import dataclasses
import unittest

from epc_control_tower.config import load_run_config
from epc_control_tower.determinism import sha256_bytes
from epc_control_tower.domain import Severity
from epc_control_tower.exporters.legacy_pbip import LegacyPbipAdapter
from epc_control_tower.exporters.legacy_projection import (
    narrow_to_ruleset,
    project_bundle,
)
from epc_control_tower.legacy_identity import LEGACY_RUN_ID
from epc_control_tower.rules import load_ruleset
from helpers import (
    legacy_compat,
    LEGACY_PROJECT_ID,
    PROJECT_ROOT,
    shipped_pipeline_result,
    widened_ruleset_bundle,
)

PROCESSED = PROJECT_ROOT / "data" / "processed"
FROZEN_RULESET = PROJECT_ROOT / "ids" / "epc_delivery_requirements_v0.1.ids"


class ConfiguredScopeTests(unittest.TestCase):
    def test_the_frozen_rule_document_is_named_in_configuration(self):
        config = load_run_config(PROJECT_ROOT)
        self.assertIsNotNone(config.legacy_ruleset_path)
        self.assertEqual(config.legacy_ruleset_path.name, FROZEN_RULESET.name)

    def test_the_frozen_document_still_declares_what_it_published(self):
        frozen = load_ruleset(FROZEN_RULESET)
        self.assertEqual(frozen.version, "0.1")
        self.assertEqual(len({r.rule_id for r in frozen.requirements}), 7)
        self.assertEqual(len(frozen.requirements), 9)


class WideningTheRuleSetTests(unittest.TestCase):
    """One extra rule, with and without the scope."""

    @classmethod
    def setUpClass(cls):
        cls.widened, cls.frozen = widened_ruleset_bundle()

    def test_the_widened_run_really_does_carry_more_rules(self):
        # If this stops being true the rest of the file proves nothing.
        self.assertEqual(len({r.rule_id for r in self.widened.ruleset.requirements}), 13)
        self.assertGreater(len(self.widened.findings), 121)

    def test_without_the_scope_every_published_key_is_destroyed(self):
        unscoped = project_bundle(self.widened, project_id=LEGACY_PROJECT_ID)
        self.assertNotEqual(unscoped.run_id, LEGACY_RUN_ID)

        published = {
            row["finding_key"]
            for row in _published_rows()
        }
        survived = published & {row.finding_key for row in unscoped.findings}
        self.assertEqual(len(survived), 0, "expected total re-keying without the scope")

    def test_without_the_scope_the_published_files_change(self):
        tables = LegacyPbipAdapter(project_id=LEGACY_PROJECT_ID).build_tables(
            self.widened
        )
        changed = [
            name
            for name, data in tables.items()
            if data != (PROCESSED / name).read_bytes()
        ]
        # models.csv and model_inventory.csv survive because they do not carry
        # a run identity; everything that does is rewritten.
        self.assertEqual(len(changed), 6)
        self.assertIn("ids_findings.csv", changed)

    def test_with_the_scope_every_published_byte_survives(self):
        tables = LegacyPbipAdapter(
            project_id=LEGACY_PROJECT_ID, frozen_ruleset=self.frozen, compat=legacy_compat()
        ).build_tables(self.widened)
        self.assertEqual(len(tables), 8)
        for name, data in sorted(tables.items()):
            with self.subTest(table=name):
                self.assertEqual(data, (PROCESSED / name).read_bytes())

    def test_with_the_scope_the_published_run_identity_survives(self):
        scoped = project_bundle(
            self.widened,
            project_id=LEGACY_PROJECT_ID,
            frozen_ruleset=self.frozen,
            compat=legacy_compat(),
        )
        self.assertEqual(scoped.run_id, LEGACY_RUN_ID)
        self.assertEqual(len(scoped.findings), 47)

    def test_with_the_scope_the_bcf_archive_survives(self):
        from epc_control_tower.bcf.schema import default_schema_dir
        from epc_control_tower.exporters.legacy_bcf import LegacyBcfExporter

        archive = LegacyBcfExporter(
            schema_dir=default_schema_dir(PROJECT_ROOT),
            project_id=LEGACY_PROJECT_ID,
            frozen_ruleset=self.frozen, compat=legacy_compat(),
        ).build_archive(self.widened)
        self.assertEqual(
            sha256_bytes(archive),
            "b3c6f51abc9647ef4baeee9f9bccd884094b362362e516778c4bf083326abc99",
        )

    def test_the_new_rule_still_reaches_the_canonical_outputs(self):
        # The scope narrows what is *published*, not what is validated. A rule
        # that produced nothing anywhere would be a pointless rule.
        rule_ids = {
            self.widened.ruleset.by_key(f.requirement_key).rule_id
            for f in self.widened.findings
        }
        self.assertIn("R-006", rule_ids)


class FrozenMetadataTests(unittest.TestCase):
    """The published rows carry the frozen rule's metadata, not the current one."""

    @classmethod
    def setUpClass(cls):
        cls.bundle = shipped_pipeline_result().bundle
        cls.frozen = load_ruleset(FROZEN_RULESET)

    def test_a_reclassified_rule_does_not_change_what_was_published(self):
        # Severity is about to become rule metadata. If a later rule set
        # reclassifies R-005 as an error, the published file must still say
        # WARNING, because that is what rule set 0.1 said.
        reclassified = dataclasses.replace(
            self.frozen,
            requirements=tuple(
                dataclasses.replace(requirement, severity=Severity.ERROR)
                if requirement.rule_id.startswith("R-005")
                else requirement
                for requirement in self.frozen.requirements
            ),
        )
        current = project_bundle(
            self.bundle,
            project_id=LEGACY_PROJECT_ID,
            frozen_ruleset=self.frozen,
            compat=legacy_compat(),
        )
        altered = project_bundle(
            self.bundle,
            project_id=LEGACY_PROJECT_ID,
            frozen_ruleset=reclassified,
            compat=legacy_compat(),
        )
        self.assertEqual(
            {row.severity for row in current.findings if row.is_issue == "true"},
            {"WARNING"},
        )
        self.assertEqual(
            {row.severity for row in altered.findings if row.is_issue == "true"},
            {"ERROR"},
        )

    def test_removing_a_published_rule_is_refused(self):
        # A rule the published contract depends on cannot be dropped or renamed
        # while the adapters exist, and saying so is better than emitting a
        # short file.
        shrunk = dataclasses.replace(
            self.bundle,
            ruleset=dataclasses.replace(
                self.bundle.ruleset,
                requirements=tuple(
                    r
                    for r in self.bundle.ruleset.requirements
                    if r.rule_id != "R-003"
                ),
            ),
        )
        with self.assertRaisesRegex(ValueError, "no longer contains"):
            narrow_to_ruleset(shrunk, self.frozen)


def _published_rows():
    from epc_control_tower.determinism import read_csv_rows

    return read_csv_rows(PROCESSED / "ids_findings.csv")


if __name__ == "__main__":
    unittest.main()
