"""Rules as data: TOML in, a rule set and an IDS document out.

Until now a rule was a function call. ``generate_ids.py`` declared its seven
specifications as module-level calls to ``add_specification`` and then asserted
that the document it had just written contained a literal list of seven
identifiers. Adding a rule meant editing Python and editing the assertion; the
severity of a rule was a prefix match on its identifier; and the metadata a
delivery requirement actually carries — who owns it, at which stage it applies,
which disciplines it binds, what it cites — had nowhere to live at all.

Here a rule is a TOML file. It carries its own metadata, and the two things
derived from it are:

* a :class:`~.domain.RuleSet`, which is what the registry routes on and what
  the validation identity is computed from; and
* an IDS document, which is what IfcTester actually executes.

The second is generated, committed, and regenerated by every run, so it is
covered by the same ``git diff --exit-code`` gate as every other artifact. It
is a build product of the rules, not a source of them.

The requirement identifier is *computed*, not declared. IfcTester labels a
reported requirement by its facet — ``Pset_WallCommon.IsExternal`` for a
property, the relation name for a ``partOf`` — and every published
``requirement_key`` is a UUIDv5 over that label. Letting a rule author type it
by hand would mean a typo silently re-keyed a published requirement, so the
label is derived from the same facet the document is compiled from.
"""

from __future__ import annotations

import tomllib
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path

from ifctester import ids

from .domain import Requirement, RuleSet, Severity
from .identity import build_requirement_key, build_ruleset_normalized_digest

__all__ = [
    "COMPLETENESS_KINDS",
    "FACET_KINDS",
    "REQUIREMENT_KINDS",
    "RuleDefinition",
    "RuleSetDefinition",
    "compile_document",
    "load_rule_definitions",
]

#: Every facet kind IDS 1.0 defines. A rule declaring anything else is rejected
#: at load time rather than producing a document IfcTester silently ignores.
FACET_KINDS = (
    "attribute",
    "classification",
    "entity",
    "material",
    "partof",
    "property",
)

#: What a rule routed to the completeness checker may require. A separate
#: vocabulary, because it is a different language: these are questions about a
#: set of models, and IDS has no way to ask one. Keeping them in the same list
#: as the IDS facets would have implied a document could carry them.
COMPLETENESS_KINDS = ("shared-across-models",)

#: Which requirement vocabulary each checker speaks. A rule naming a checker
#: that is not here is rejected when the library loads: a rule the pipeline
#: cannot route is a rule that would otherwise be silently skipped, and a
#: silently skipped delivery requirement is the worst outcome available.
REQUIREMENT_KINDS = {
    "ids": FACET_KINDS,
    "completeness": COMPLETENESS_KINDS,
}

RULESET_FILENAME = "ruleset.toml"


def _read_toml(path: Path) -> dict:
    with path.open("rb") as stream:
        return tomllib.load(stream)


def _require(document: dict, key: str, source: Path):
    if key not in document:
        raise ValueError(f"{source} is missing required key {key!r}")
    return document[key]


def _restriction(value) -> object:
    """Turn a declared value into a simple value or an IDS restriction.

    A plain string is a literal. A table becomes an ``xs:restriction``, which is
    how IDS expresses "one of these", "matching this pattern", or a numeric
    bound — the value constraints that make up the seventh thing IDS 1.0 can
    say and that this rule set could not previously express at all.
    """

    if value is None or isinstance(value, str):
        return value
    if isinstance(value, dict):
        options = {}
        if "enumeration" in value:
            options["enumeration"] = list(value["enumeration"])
        if "pattern" in value:
            options["pattern"] = str(value["pattern"])
        for bound in ("minInclusive", "maxInclusive", "minExclusive", "maxExclusive"):
            if bound in value:
                options[bound] = value[bound]
        if not options:
            raise ValueError(f"Unsupported value restriction: {value!r}")
        return ids.Restriction(options=options, base=str(value.get("base", "string")))
    raise ValueError(f"Unsupported value declaration: {value!r}")


@dataclass(frozen=True, slots=True)
class FacetDefinition:
    """One declared facet, in either the applicability or the requirements."""

    kind: str
    values: dict

    def build(self):
        """Construct the IfcTester facet this declaration describes."""

        kind = self.kind
        declared = dict(self.values)
        cardinality = declared.pop("cardinality", None)
        instructions = declared.pop("instructions", None)
        extra = {}
        if cardinality is not None:
            extra["cardinality"] = cardinality
        if instructions is not None:
            extra["instructions"] = instructions

        if kind == "entity":
            return ids.Entity(
                name=_restriction(declared.pop("name")),
                predefinedType=_restriction(declared.pop("predefinedType", None)),
                **extra,
            )
        if kind == "attribute":
            return ids.Attribute(
                name=_restriction(declared.pop("name")),
                value=_restriction(declared.pop("value", None)),
                **extra,
            )
        if kind == "classification":
            return ids.Classification(
                system=_restriction(declared.pop("system", None)),
                value=_restriction(declared.pop("value", None)),
                uri=declared.pop("uri", None),
                **extra,
            )
        if kind == "property":
            return ids.Property(
                propertySet=_restriction(declared.pop("propertySet")),
                baseName=_restriction(declared.pop("baseName")),
                value=_restriction(declared.pop("value", None)),
                dataType=declared.pop("dataType", None),
                uri=declared.pop("uri", None),
                **extra,
            )
        if kind == "material":
            return ids.Material(
                value=_restriction(declared.pop("value", None)),
                uri=declared.pop("uri", None),
                **extra,
            )
        if kind == "partof":
            return ids.PartOf(
                name=_restriction(declared.pop("name")),
                predefinedType=_restriction(declared.pop("predefinedType", None)),
                relation=declared.pop("relation"),
                **extra,
            )
        raise ValueError(f"Unknown facet kind {kind!r}; expected one of {list(FACET_KINDS)}")


@dataclass(frozen=True, slots=True)
class RuleDefinition:
    """One rule, as its author declared it."""

    rule_id: str
    title: str
    description: str
    applicability: tuple[FacetDefinition, ...]
    requirements: tuple[FacetDefinition, ...]
    checker: str = "ids"
    severity: Severity = Severity.ERROR
    owner_role: str = ""
    stage: str = ""
    discipline_scope: tuple[str, ...] = ()
    citation: str = ""
    ifc_version: tuple[str, ...] = ("IFC4",)

    @property
    def facet_kinds(self) -> tuple[str, ...]:
        return tuple(facet.kind for facet in self.requirements)


@dataclass(frozen=True, slots=True)
class RuleSetDefinition:
    ruleset_id: str
    version: str
    title: str
    description: str = ""
    purpose: str = ""
    milestone: str = ""
    rules: tuple[RuleDefinition, ...] = field(default=())


def _facets(
    entries,
    source: Path,
    label: str,
    allowed: tuple[str, ...] = FACET_KINDS,
) -> tuple[FacetDefinition, ...]:
    if not isinstance(entries, list) or not entries:
        raise ValueError(f"{source}: at least one [[{label}]] entry is required")
    facets = []
    for entry in entries:
        if not isinstance(entry, dict):
            raise ValueError(f"{source}: each [[{label}]] entry must be a table")
        declared = dict(entry)
        kind = str(declared.pop("facet", "")).lower()
        if kind not in allowed:
            raise ValueError(
                f"{source}: {label} declares facet {kind!r}; expected one of "
                f"{list(allowed)}"
            )
        facets.append(FacetDefinition(kind=kind, values=declared))
    return tuple(facets)


def load_rule_definitions(directory: Path) -> RuleSetDefinition:
    """Read a rule directory: one ``ruleset.toml`` and one file per rule."""

    directory = Path(directory)
    meta_path = directory / RULESET_FILENAME
    if not meta_path.is_file():
        raise FileNotFoundError(f"No {RULESET_FILENAME} in {directory}")

    meta = _read_toml(meta_path)
    section = _require(meta, "ruleset", meta_path)

    rules: list[RuleDefinition] = []
    seen: set[str] = set()
    # Sorted, so a rule set is the same rule set however the filesystem chose
    # to order its entries.
    for path in sorted(directory.glob("*.toml")):
        if path.name == RULESET_FILENAME:
            continue
        document = _read_toml(path)
        rule_id = str(_require(document, "rule_id", path))
        if rule_id in seen:
            raise ValueError(f"{path}: duplicate rule_id {rule_id!r}")
        seen.add(rule_id)

        checker = str(document.get("checker", "ids"))
        if checker not in REQUIREMENT_KINDS:
            raise ValueError(
                f"{path}: rule is routed to checker {checker!r}; this library knows "
                f"{sorted(REQUIREMENT_KINDS)}"
            )

        severity_name = str(document.get("severity", "ERROR")).upper()
        try:
            severity = Severity[severity_name]
        except KeyError:
            raise ValueError(
                f"{path}: severity {severity_name!r} is not one of "
                f"{[s.name for s in Severity]}"
            ) from None

        rules.append(
            RuleDefinition(
                rule_id=rule_id,
                title=str(_require(document, "title", path)),
                description=str(document.get("description", "")),
                applicability=_facets(
                    document.get("applicability", []), path, "applicability"
                ),
                requirements=_facets(
                    document.get("requirements", []),
                    path,
                    "requirements",
                    REQUIREMENT_KINDS[checker],
                ),
                checker=checker,
                severity=severity,
                owner_role=str(document.get("owner_role", "")),
                stage=str(document.get("stage", "")),
                discipline_scope=tuple(
                    str(item) for item in document.get("discipline_scope", [])
                ),
                citation=str(document.get("citation", "")),
                ifc_version=tuple(
                    str(item) for item in document.get("ifc_version", ["IFC4"])
                ),
            )
        )

    if not rules:
        raise ValueError(f"{directory}: declares no rules")

    return RuleSetDefinition(
        ruleset_id=str(_require(section, "ruleset_id", meta_path)),
        version=str(_require(section, "version", meta_path)),
        title=str(_require(section, "title", meta_path)),
        description=str(section.get("description", "")),
        purpose=str(section.get("purpose", "")),
        milestone=str(section.get("milestone", "")),
        rules=tuple(rules),
    )


def compile_document(definition: RuleSetDefinition):
    """Build the IDS document, the rule set, and each requirement's wording.

    All three come out of one pass because they have to agree: the label
    IfcTester will report, the key derived from that label, and the sentence
    published as ``expected`` are three views of the same declared facet.

    The rule set covers **every** rule; the document covers only the ones
    routed to the IDS checker. Compiling a completeness rule into an IDS
    document would be writing a sentence in a language that cannot express it,
    and IfcTester would then evaluate a specification nobody meant it to see.
    """

    from .checkers.ids_checker import requirement_label

    document = ids.Ids(
        title=definition.title,
        version=definition.version,
        description=definition.description,
        purpose=definition.purpose,
        milestone=definition.milestone,
    )

    requirements: list[Requirement] = []
    expectations: dict[str, str] = {}

    for rule in definition.rules:
        if rule.checker != "ids":
            for requirement in _foreign_requirements(rule):
                requirements.append(requirement)
                expectations[requirement.requirement_key] = (
                    requirement.requirement_label
                )
            continue

        specification = ids.Specification(
            name=rule.title,
            identifier=rule.rule_id,
            description=rule.description,
            ifcVersion=list(rule.ifc_version),
            # A model with no applicable elements reports N/A rather than
            # failing; whether that counts as compliance is decided downstream.
            minOccurs=0,
            maxOccurs="unbounded",
        )
        for facet in rule.applicability:
            specification.applicability.append(facet.build())

        seen_labels: set[str] = set()
        for facet in rule.requirements:
            built = facet.build()
            specification.requirements.append(built)

            requirement_id = requirement_label(built)
            if requirement_id in seen_labels:
                raise ValueError(
                    f"{rule.rule_id}: two requirements both label as "
                    f"{requirement_id!r}, so they would share a key"
                )
            seen_labels.add(requirement_id)

            key = build_requirement_key(rule.rule_id, requirement_id)
            requirements.append(
                Requirement(
                    requirement_key=key,
                    rule_id=rule.rule_id,
                    requirement_id=requirement_id,
                    specification_label=f"{rule.rule_id}: {rule.title}",
                    requirement_label=requirement_id,
                    checker=rule.checker,
                    facet_kinds=(facet.kind,),
                    severity=rule.severity,
                    owner_role=rule.owner_role,
                    stage=rule.stage,
                    discipline_scope=rule.discipline_scope,
                    citation=rule.citation,
                )
            )
            expectations[key] = (
                built.to_string("requirement", specification, built) or requirement_id
            )

        document.specifications.append(specification)

    ruleset = RuleSet(
        ruleset_id=definition.ruleset_id,
        version=definition.version,
        normalized_digest=build_ruleset_normalized_digest(
            ruleset_id=definition.ruleset_id,
            version=definition.version,
            requirements=requirements,
        ),
        requirements=tuple(requirements),
    )
    return document, ruleset, expectations


def _foreign_requirements(rule: RuleDefinition) -> list[Requirement]:
    """Requirements for a rule some other checker evaluates.

    The identifier is the declared kind, so it is stable, readable, and — like
    an IDS requirement's — derived rather than typed by the rule author. Two
    requirements of the same kind in one rule would share a key, so that is
    rejected here rather than discovered later as a collision.

    The checker's parameters stay in the rule file and the checker reads them
    from there, exactly as the IDS checker reads its facets back out of the
    document it compiled. A requirement carries identity and metadata; it is
    not a payload every checker has to agree on the shape of.
    """

    built: list[Requirement] = []
    seen: set[str] = set()
    for facet in rule.requirements:
        if facet.kind in seen:
            raise ValueError(
                f"{rule.rule_id}: two {facet.kind!r} requirements would share a key"
            )
        seen.add(facet.kind)
        built.append(
            Requirement(
                requirement_key=build_requirement_key(rule.rule_id, facet.kind),
                rule_id=rule.rule_id,
                requirement_id=facet.kind,
                specification_label=f"{rule.rule_id}: {rule.title}",
                requirement_label=str(
                    facet.values.get("instructions") or facet.kind
                ),
                checker=rule.checker,
                facet_kinds=(facet.kind,),
                severity=rule.severity,
                owner_role=rule.owner_role,
                stage=rule.stage,
                discipline_scope=rule.discipline_scope,
                citation=rule.citation,
            )
        )
    return built


def declared_rule_ids(definition: RuleSetDefinition) -> Sequence[str]:
    return [rule.rule_id for rule in definition.rules]
